<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<title>Laporan Absensi {{ $period }}</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica', Arial, sans-serif; color: #1e1b4b; font-size: 10pt; }
    .header { padding: 20px 0; border-bottom: 3px solid #7c3aed; margin-bottom: 16px; }
    .header h1 { color: #7c3aed; font-size: 22pt; font-weight: bold; }
    .header .subtitle { color: #64748b; font-size: 10pt; margin-top: 4px; }
    .meta { display: table; width: 100%; margin-bottom: 16px; }
    .meta div { display: table-cell; padding: 8px 12px; background: #f5f3ff; border-radius: 6px; font-size: 9pt; }
    .meta .label { color: #7c3aed; font-weight: bold; text-transform: uppercase; font-size: 8pt; }
    table { width: 100%; border-collapse: collapse; font-size: 8.5pt; }
    thead { background: linear-gradient(135deg, #7c3aed, #5b21b6); color: white; }
    thead th { padding: 8px 6px; text-align: left; font-weight: bold; font-size: 8pt; text-transform: uppercase; }
    tbody td { padding: 6px; border-bottom: 1px solid #e5e7eb; }
    tbody tr:nth-child(even) { background: #f9fafb; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 7.5pt; font-weight: bold; }
    .badge-in  { background: #d1fae5; color: #065f46; }
    .badge-out { background: #cffafe; color: #155e75; }
    .badge-late { background: #fef3c7; color: #92400e; }
    .badge-on { background: #d1fae5; color: #065f46; }
    .badge-yes { background: #d1fae5; color: #065f46; }
    .badge-no { background: #fee2e2; color: #991b1b; }
    .footer { margin-top: 20px; text-align: center; color: #9ca3af; font-size: 8pt; }
    .summary { margin-top: 16px; padding: 12px; background: #f5f3ff; border-radius: 6px; }
    .summary strong { color: #7c3aed; }
</style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name', 'Presensi') }}</h1>
        <p class="subtitle">Laporan Absensi — Periode {{ $period }}</p>
    </div>

    <div class="meta">
        <div><span class="label">Periode</span><br><strong>{{ $period }}</strong></div>
        <div><span class="label">Total Record</span><br><strong>{{ count($items) }}</strong></div>
        <div><span class="label">Generated</span><br><strong>{{ now()->translatedFormat('d M Y H:i') }}</strong></div>
        <div><span class="label">Generated By</span><br><strong>{{ $generatedBy }}</strong></div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 28px;">#</th>
                <th>Tanggal</th>
                <th>Waktu</th>
                <th>Tipe</th>
                <th>Nama</th>
                <th>NIK</th>
                <th>Posisi</th>
                <th>Status</th>
                <th>Face</th>
                <th>Score</th>
                <th>Lokasi</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($items as $i => $r)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $r->date->format('d M Y') }}<br><small style="color:#64748b">{{ $r->date->locale('id')->translatedFormat('l') }}</small></td>
                    <td>{{ $r->time }}</td>
                    <td><span class="badge {{ $r->type === 'in' ? 'badge-in' : 'badge-out' }}">{{ strtoupper($r->type) }}</span></td>
                    <td>{{ $r->user->name ?? '-' }}</td>
                    <td>{{ $r->user->nik ?? '-' }}</td>
                    <td>{{ $r->user->position ?? '-' }}</td>
                    <td><span class="badge {{ $r->status === 'late' ? 'badge-late' : 'badge-on' }}">{{ $r->status }}</span></td>
                    <td><span class="badge {{ $r->face_verified ? 'badge-yes' : 'badge-no' }}">{{ $r->face_verified ? 'YES' : 'NO' }}</span></td>
                    <td>{{ $r->face_score ? round($r->face_score * 100, 1) . '%' : '-' }}</td>
                    <td style="font-size: 7.5pt;">{{ $r->location ?? '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="11" style="text-align: center; padding: 24px; color: #9ca3af;">Tidak ada data</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <strong>Ringkasan:</strong>
        Hadir: {{ $items->where('type', 'in')->count() }} •
        Pulang: {{ $items->where('type', 'out')->count() }} •
        Telat: {{ $items->where('status', 'late')->count() }} •
        Face Verified: {{ $items->where('face_verified', true)->count() }}
    </div>

    <div class="footer">
        © {{ date('Y') }} {{ config('app.name') }} — Generated on {{ now()->format('d M Y H:i:s') }}
    </div>
</body>
</html>
